"""
Training hyperparameter presets for each training stage.

Each dict unpacks into ``YOLO.train(**preset)``.
"""

# ── Stage A: COCO Pretraining (base weights) ────────────────────
# Not a training stage itself — maps to Ultralytics official weights.
# Download: https://docs.ultralytics.com/models/yolo11/
COCO_PRETRAINED = {
    "yolo11n": "yolo11n.pt",   # 2.6M params — ROI proposer
    "yolo11s": "yolo11s.pt",   # 9.5M params — vehicle-side
    "yolo11m": "yolo11m.pt",   # 20.1M params — ground-side
}

ROI_TRAIN_CONFIG = {
    # NOTE: "data" path must be overridden to point to your actual dataset YAML.
    # The default is a placeholder — see scripts/setup_autodl.sh for setup.
    "data": "datasets/roi/roi_data.yaml",
    "epochs": 200,
    "imgsz": 640,
    "batch": 32,
    "optimizer": "SGD",
    "lr0": 0.01,
    "lrf": 0.01,
    "momentum": 0.937,
    "weight_decay": 0.0005,
    "warmup_epochs": 3,
    "warmup_momentum": 0.8,
    "warmup_bias_lr": 0.1,
    "cos_lr": True,
    "mosaic": 0.8,
    "mixup": 0.1,
    "copy_paste": 0.0,
    "hsv_h": 0.015,
    "hsv_s": 0.7,
    "hsv_v": 0.4,
    "degrees": 5.0,
    "translate": 0.1,
    "scale": 0.5,
    "shear": 2.0,
    "perspective": 0.0005,
    "flipud": 0.0,
    "fliplr": 0.5,
    "close_mosaic": 0,
    "device": "0",
    "workers": 4,
    "cache": "ram",
    "amp": True,
}

DEFECT_WARMUP_CONFIG = {
    "epochs": 50,
    "imgsz": 1024,
    "batch": 16,
    "optimizer": "SGD",
    "lr0": 0.001,
    "lrf": 1.0,
    "momentum": 0.937,
    "weight_decay": 0.0005,
    "warmup_epochs": 3,
    "warmup_momentum": 0.8,
    "warmup_bias_lr": 0.1,
    "cos_lr": False,
    "mosaic": 0.5,
    "mixup": 0.0,
    "copy_paste": 0.0,
    "hsv_h": 0.015,
    "hsv_s": 0.7,
    "hsv_v": 0.6,
    "degrees": 5.0,
    "translate": 0.15,
    "scale": 0.5,
    "shear": 2.0,
    "perspective": 0.0005,
    "flipud": 0.0,
    "fliplr": 0.5,
    "close_mosaic": 0,
    "freeze": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "device": "0",
    "workers": 4,
    "cache": "ram",
    "amp": True,
}

DEFECT_FULL_TRAIN_CONFIG = {
    "epochs": 200,
    "imgsz": 1024,
    "batch": 16,
    "optimizer": "AdamW",
    "lr0": 0.001,
    "lrf": 0.01,
    "momentum": 0.937,
    "weight_decay": 0.0001,
    "cos_lr": True,
    "mosaic": 0.8,
    "mixup": 0.15,
    "copy_paste": 0.6,
    "copy_paste_mode": "flip",
    "hsv_h": 0.015,
    "hsv_s": 0.7,
    "hsv_v": 0.6,
    "degrees": 5.0,
    "translate": 0.15,
    "scale": 0.5,
    "shear": 2.0,
    "perspective": 0.0005,
    "flipud": 0.0,
    "fliplr": 0.5,
    "close_mosaic": 190,
    "device": "0",
    "workers": 4,
    "cache": "ram",
    "amp": True,
}

DEFECT_FINETUNE_CONFIG = {
    "epochs": 50,
    "imgsz": 1024,
    "batch": 8,
    "optimizer": "AdamW",
    "lr0": 0.0001,
    "lrf": 0.1,
    "momentum": 0.937,
    "weight_decay": 0.0001,
    "cos_lr": False,
    "mosaic": 0.0,
    "mixup": 0.0,
    "copy_paste": 0.4,
    "copy_paste_mode": "flip",
    "hsv_h": 0.01,
    "hsv_s": 0.4,
    "hsv_v": 0.3,
    "degrees": 2.0,
    "translate": 0.1,
    "scale": 0.3,
    "shear": 1.0,
    "perspective": 0.0,
    "flipud": 0.0,
    "fliplr": 0.3,
    "close_mosaic": 0,
    "device": "0",
    "workers": 4,
    "cache": "ram",
    "amp": True,
}
