"""
Training hyperparameter presets for each training stage.

Each dict unpacks into ``YOLO.train(**preset)``.
"""

ROI_TRAIN_CONFIG = {
    "data": "datasets/roi/roi_data.yaml",
    "epochs": 200,
    "imgsz": 640,
    "batch": 32,
    "optimizer": "SGD",
    "lr0": 0.01,
    "lrf": 0.01,
    "momentum": 0.937,
    "weight_decay": 0.0005,
    "warmup_epochs": 3,
    "warmup_momentum": 0.8,
    "warmup_bias_lr": 0.1,
    "cos_lr": True,
    "mosaic": 0.8,
    "mixup": 0.1,
    "copy_paste": 0.0,
    "hsv_h": 0.015,
    "hsv_s": 0.7,
    "hsv_v": 0.4,
    "degrees": 5.0,
    "translate": 0.1,
    "scale": 0.5,
    "shear": 2.0,
    "perspective": 0.0005,
    "flipud": 0.0,
    "fliplr": 0.5,
    "close_mosaic": 0,
    "device": "0",
    "workers": 4,
    "cache": "ram",
    "amp": True,
}

DEFECT_WARMUP_CONFIG = {
    "epochs": 50,
    "imgsz": 1024,
    "batch": 16,
    "optimizer": "SGD",
    "lr0": 0.001,
    "lrf": 1.0,
    "momentum": 0.937,
    "weight_decay": 0.0005,
    "warmup_epochs": 3,
    "warmup_momentum": 0.8,
    "warmup_bias_lr": 0.1,
    "cos_lr": False,
    "mosaic": 0.5,
    "mixup": 0.0,
    "copy_paste": 0.0,
    "hsv_h": 0.015,
    "hsv_s": 0.7,
    "hsv_v": 0.6,
    "degrees": 5.0,
    "translate": 0.15,
    "scale": 0.5,
    "shear": 2.0,
    "perspective": 0.0005,
    "flipud": 0.0,
    "fliplr": 0.5,
    "close_mosaic": 0,
    "freeze": [
        "model.0.", "model.1.", "model.2.", "model.3.",
        "model.4.", "model.5.", "model.6.", "model.7.",
        "model.8.", "model.9.", "model.10.",
    ],
    "device": "0",
    "workers": 4,
    "cache": "ram",
    "amp": True,
}

DEFECT_FULL_TRAIN_CONFIG = {
    "epochs": 200,
    "imgsz": 1024,
    "batch": 16,
    "optimizer": "AdamW",
    "lr0": 0.001,
    "lrf": 0.01,
    "momentum": 0.937,
    "weight_decay": 0.0001,
    "cos_lr": True,
    "mosaic": 0.8,
    "mixup": 0.15,
    "copy_paste": 0.6,
    "copy_paste_mode": "flip",
    "hsv_h": 0.015,
    "hsv_s": 0.7,
    "hsv_v": 0.6,
    "degrees": 5.0,
    "translate": 0.15,
    "scale": 0.5,
    "shear": 2.0,
    "perspective": 0.0005,
    "flipud": 0.0,
    "fliplr": 0.5,
    "close_mosaic": 200,
    "device": "0",
    "workers": 4,
    "cache": "ram",
    "amp": True,
}

DEFECT_FINETUNE_CONFIG = {
    "epochs": 50,
    "imgsz": 1024,
    "batch": 8,
    "optimizer": "AdamW",
    "lr0": 0.0001,
    "lrf": 0.1,
    "momentum": 0.937,
    "weight_decay": 0.0001,
    "cos_lr": False,
    "mosaic": 0.0,
    "mixup": 0.0,
    "copy_paste": 0.4,
    "copy_paste_mode": "flip",
    "hsv_h": 0.01,
    "hsv_s": 0.4,
    "hsv_v": 0.3,
    "degrees": 2.0,
    "translate": 0.1,
    "scale": 0.3,
    "shear": 1.0,
    "perspective": 0.0,
    "flipud": 0.0,
    "fliplr": 0.3,
    "close_mosaic": 0,
    "device": "0",
    "workers": 4,
    "cache": "ram",
    "amp": True,
}
