train: train/images
val: val/images
nc: 12
names:
- VHBNM
- VHBNL
- SVHBNM
- SVHBNL
- SVHTNL
- CBHPM
- CBVPM
- RHTBNM
- RHTBNL
- BSBM
- INSD
- DRPS
epochs: 60
imgsz: 1280
batch: 12
optimizer: AdamW
lr0: 0.0002
lrf: 0.05
warmup_epochs: 3
warmup_momentum: 0.5
warmup_bias_lr: 0.0002
weight_decay: 0.00075
cos_lr: true
patience: 20
mosaic: 0.5
mixup: 0.1
copy_paste: 0.5
erasing: 0.0
hsv_h: 0.015
hsv_s: 0.3
hsv_v: 0.3
degrees: 2.0
translate: 0.05
scale: 0.2
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
close_mosaic: 25
auto_augment: none
amp: true
cache: false
save_period: 5
path: data/subway_crops
seed: 0
conf: 0.01
multi_scale: 0.0
fl_gamma: 2.0
class_weights: []
iou_type: WIoU